---
name: create_project_subscription_graphql_endpoint
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133308
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429339
milestone: '16.6'
type: development
group: group::pipeline execution
default_enabled: false
