---
name: global_ci_catalog 
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133885
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427940 
milestone: '16.6'
type: development
group: group::pipeline authoring 
default_enabled: false
