---
name: product_analytics_usage_quota
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133781
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427838
milestone: '16.6'
type: development
group: group::product analytics
default_enabled: false
