---
name: project_overwrite_service_tracking
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350889
milestone: '14.1'
type: development
group: group::import and integrate
default_enabled: false
