---
name: advanced_epic_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124072
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/415684
milestone: '16.3'
type: development
group: group::global search
default_enabled: false
