---
name: ci_catalog_components_tab
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132764
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426443
milestone: '16.5'
type: development
group: group::pipeline authoring
default_enabled: false
