---
name: ci_tanukey_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131224
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427026
milestone: '16.6'
type: development
group: group::pipeline security
default_enabled: false
