---
name: code_completion_split_by_language
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133580
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427598
milestone: '16.5'
type: development
group: group::code creation
default_enabled: false
