---
name: code_completion_anthropic
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132369
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426111
milestone: '16.5'
type: development
group: group::code creation
default_enabled: false
