---
name: code_generation_no_comment_prefix
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131524
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424879
milestone: '16.4'
type: development
group: group::code creation
default_enabled: false
