---
name: compliance_violation_csv_export
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/120636
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424447
milestone: '16.4'
type: development
group: group::compliance
default_enabled: true
