---
name: cs_connect_with_sales
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130351
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423552
milestone: '16.4'
type: development
group: group::acquisition
default_enabled: false
