---
name: dependency_scanning_on_advisory_ingestion
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127805
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419550
milestone: '16.3'
type: development
group: group::composition analysis
default_enabled: true
