---
name: enable_hamilton_in_user_preferences
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127881
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419821
milestone: '16.3'
type: development
group: group::purchase
default_enabled: false
