---
name: group_vulnerabilities_optimized_query
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127180
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426394
milestone: '16.5'
type: development
group: group::threat insights
default_enabled: false
