---
name: identity_verification_auto_ban
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/126008
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/417557
milestone: "16.3"
type: development
group: group::anti-abuse
default_enabled: true
