---
name: log_advanced_search_cluster_health_elastic
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127731
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/420295
milestone: '16.3'
type: development
group: group::global search
default_enabled: false
