---
name: scan_result_any_merge_request
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130630
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423988
milestone: '16.4'
type: development
group: group::security policies
default_enabled: false
