---
name: scan_result_policies_block_unprotecting_branches
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130653
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423901
milestone: '16.4'
type: development
group: group::security policies
default_enabled: false
