name: group_deploy_token_creation_failed
description: Audit event triggered when a groups deploy token fails to create
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/363087
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/93091
milestone: '15.3'
feature_category: continuous_delivery
saved_to_database: true
streamed: true
