---
key_path: usage_activity_by_stage_monthly.secure.secret_detection_scans
description: Number of Secret Detection security scans run
product_section: sec
product_stage: secure
product_group: static_analysis
value_type: number
status: active
milestone: "<13.9"
time_frame: 28d
data_source: database
instrumentation_class: CountSecurityScansMetric
options:
  scan_type: secret_detection
data_category: operational
distribution:
  - ee
tier:
  - ultimate
