---
key_path: redis_hll_counters.govern.users_creating_merge_requests_with_security_policies_monthly
description: Unique count of users creating merge requests with security policies in a given month
product_section: sec
product_stage: govern
product_group: security_policies
value_type: number
status: active
milestone: "16.3"
introduced_by_url:
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
performance_indicator_type: []
distribution:
- ee
tier:
- ultimate
options:
  events:
    - users_creating_merge_requests_with_security_policies
