---
include:
  - local: .gitlab/ci/cng/main.gitlab-ci.yml

release-environments-build-cng-env:
  extends: .build-cng-env
  allow_failure: true

release-environments-build-cng:
  extends: .build-cng
  needs: ["release-environments-build-cng-env"]
  variables:
    IMAGE_TAG_EXT: "-${CI_COMMIT_SHORT_SHA}"
  allow_failure: true

release-environments-deploy-env:
  allow_failure: true
  stage: deploy
  needs: ["release-environments-build-cng"]
  variables:
    DEPLOY_ENV: deploy.env
  script:
    - ./scripts/construct-release-environments-versions.rb > $DEPLOY_ENV
  artifacts:
    reports:
      dotenv: $DEPLOY_ENV
    paths:
      - $DEPLOY_ENV
    expire_in: 7 days
    when: always

release-environments-deploy:
  allow_failure: true
  stage: deploy
  needs: ["release-environments-deploy-env"]
  inherit:
    variables: false
  variables:
    VERSIONS: "${VERSIONS}"
    ENVIRONMENT: "${ENVIRONMENT}"
  trigger:
    project: gitlab-com/gl-infra/release-environments
    branch: main
    strategy: depend
