---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.ldap_admin_sync_enabled
description: Whether LDAP admin sync is enabled
product_section: sec
product_stage: govern
product_group: authentication
value_type: boolean
status: active
time_frame: none
data_source: system
distribution:
- ee
tier:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
