---
data_category: optional
key_path: counts.ldap_users
description: Number of users that are linked to LDAP
product_section: sec
product_stage: govern
product_group: authentication
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ee
tier:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
